package com.borealnetwork.allensharedui.theme

import androidx.compose.ui.graphics.Color

//generated by https://m3.material.io/theme-builder#/custom
//Color palette was taken here: https://colorhunt.co/palettes/popular

val md_theme_light_secondary = Color(0xFF00696E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF221B00)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF221B00)

val md_theme_dark_primary = Color(0xFF55D6F4)
val md_theme_dark_onPrimary = Color(0xFF003640)
val md_theme_dark_secondary = Color(0xFF4CD9E2)
val md_theme_dark_onSecondary = Color(0xFF00373A)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_background = Color(0xFF221B00)
val md_theme_dark_onBackground = Color(0xFFFFE264)
val md_theme_dark_surface = Color(0xFF221B00)
val md_theme_dark_onSurface = Color(0xFFFFE264)

val PrimaryColor = Color(0xFF348FDD)
val PrimaryEndColor = Color(0xFF95C1FB)
val Purple200 = Color(0xFFBB86FC)
val Purple500 = Color(0xFF6200EE)
val Purple700 = Color(0xFF3700B3)
val Teal200 = Color(0xFF03DAC5)
val StarColor = Color(0xFFF7CF52)
val GrayBorder = Color(0xFFBABBBD)
val GrayBorderLightSeller = Color(0xFFF0F0F0)
val GrayHomeSellerLetter = Color(0xFF515259)
val GrayBorderLight = Color(0xFFEFEFEF)
val GrayBorderSearch = Color(0xFFD9D9DD)
val GrayLetterHint = Color(0xFFA0A0A0)
val GrayBackgroundSelector = Color(0xFFF7F7F7)
val GraySubtitleBottom = Color(0xFF858585)
val GrayLetterShipping = Color(0xFF909090)
val GrayStrong = Color(0xFF707070)
val GraySinceTo = Color(0xFFA9A9A9)
val GrayBorderThin = Color(0xFFE5E5E5)
val GraySelector = Color(0xFFF8F8F8)
val GrayBackgroundSearch = Color(0xFFF7F9F8)
val GrayBackgroundMain = Color(0xFFF7F9F8)
val GrayInactiveIndicator = Color(0xFFDDD9E7)
val GrayCategoryBackground = Color(0xFFF0F3F7)
val GrayBrandingBackground = Color(0xFFECF3FC)
val GrayMedium = Color(0xFF4B4B4B)
val GrayLetterSeeAll = Color(0xFF9FA0A8)
val GrayLetterDrawer = Color(0xFFB5B6BA)
val GrayLetterCategoryProduct = Color(0xFFDBDBDB)
val GrayLetterArrow = Color(0xFFC2C3C1)
val GreenStrong = Color(0xFF51BC9D)
val SuccessColor = Color(0xFF6EC46A)
val WarningColor = Color(0xFFF7C65A)
val ErrorColor = Color(0xFFEA6965)
val RedStartColor = Color(0xFFEA6965)
val RedEndColor = Color(0xFFF5B3B3)
val OrangeStrong = Color(0xFFD46743)
val OrangeMedium = Color(0xFFF2714C)
val OrangeTransparent = Color(0xFFEFC3B4)
val OrangeBackground = Color(0xFFFDEFEA)
val OrangeTransparentLow = Color(0x1BEFC3B4)
val GreenTransparent = Color(0x379FFAA9)
val BlueTransparent = Color(0x54C7E1F7)
val GrayBackgroundDrawerDismiss = Color(0xFFF1F5F8)
val BlueStatusLineColor = Color(0xFFBDCEF4)
val CategoryBackgroundSelectorOne = Color(0xFFE6EDDB)
val CategoryBackgroundSelectorTwo = Color(0xFFDAE1F4)
val CategoryBackgroundSelectorThree = Color(0xFFF2DFE6)
val FavoriteUnselectedColor = Color(0xFFFAF6FF)
val FavoriteSelectedColor = Color(0xFFB691FF)

val categorySelectorColors = listOf(
    CategoryBackgroundSelectorOne,
    CategoryBackgroundSelectorTwo,
    CategoryBackgroundSelectorThree
)

val startColors = arrayOf(
    Color(0xFF39add1),  // light blue [0]
    Color(0xFF3079ab),  // dark blue [1]
    Color(0xFFc25975),  // mauve [2]
    Color(0xFFe15258),  // red
    Color(0xFFf9845b),  // orange
    Color(0xFF838cc7),  // lavender
    Color(0xFF7d669e),  // purple
    Color(0xFF53bbb4),  // aqua
    Color(0xFF51b46d),  // green
    Color(0xFFe0ab18),  // mustard
    Color(0xFF637a91),  // dark gray
    Color(0xFFf092b0),  // pink
    Color(0xFFb7c0c7) // light gray
)

val endColors = arrayOf(
    Color(0xFF3079ab),  //dark blue  [0]
    Color(0xFF39add1),  // light blue [1]
    Color(0xFFe0ab18),  // mustard [2]
    Color(0xFF637a91),  // dark gray
    Color(0xFFf092b0),  // pink
    Color(0xFFb7c0c7),  // light gray
    Color(0xFFc25975),  // mauve
    Color(0xFF51b46d),  // green
    Color(0xFFe15258),  // red
    Color(0xFFf9845b),  // orange
    Color(0xFF838cc7),  // lavender
    Color(0xFF7d669e), // purple
    Color(0xFF53bbb4)
)